[package]
name = "lush"
description = "LuSH is a lua for shell scripts - embedded in a single binary, easy to share, to run everywhere"
version = "0.1.1-pre-alpha"
edition = "2021"
authors = ["Thiago Massari Guedes"]
license = "Apache-2.0"
homepage = "https://gitlab.com/thiagomg/lush"
repository = "https://gitlab.com/thiagomg/lush"

[dependencies]
mlua = { version = "0.9.9", features = ["lua54", "vendored"] }
zip = { version = "2.1.3", features = ["deflate"] }
anyhow = "1.0.86"
whoami = "1.5.1"
clap = { version = "4.5.8", features = ["derive"] }