[package]
name = "lush"
description = "LuSH is a lua for shell scripts - embedded in a single binary, easy to share, to run everywhere"
version = "0.1.8"
edition = "2021"
authors = ["Thiago Massari Guedes"]
license = "Apache-2.0"
homepage = "https://gitlab.com/thiagomg/lush"
repository = "https://gitlab.com/thiagomg/lush"

[dependencies]
mlua = { version = "0.9.9", features = ["vendored", "lua54"] }
zip = { version = "2.2.0", features = ["deflate"] }
anyhow = "1.0.89"
whoami = "1.5.2"
clap = { version = "4.5.19", features = ["derive"] }
regex = "1.11.0"
colored = "2.1.0"
sysinfo = "0.32.0"
